config/routes.rb
Rails.application.routes.draw do
    mount Shoppe::Engine => "/admin"
  
    get 'products' => 'products#categories', :as => 'catalogue'
    get 'products/filter' => 'products#filter', :as => 'product_filter'
    get 'products/:category_id' => 'products#index', :as => 'products'
    get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
    post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
    

    #
    # Order status
    #
    get 'order/:token' => 'orders#status', :as => 'order_status'

    #
    # Basket
    #
    get 'basket' => 'orders#show', :as => 'basket'
    delete 'basket' => 'orders#destroy', :as => 'empty_basket'
    post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
    delete 'basket/:order_item_id' => 'orders#change_item_quantity'
    delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
    #
    # Checkout
    #
    match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
    match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
    match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch, :post]
    match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]
  
    #
    # Static pages
    #
    #get ':action', :controller => 'pages', :as => 'page'
  
    # 
    # Homepage
    #
    root :to => 'pages#home'
end

app/views/layouts/shared/_app_icons.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_url 'app_icons/apple-icon-57x57.png'%>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_url 'app_icons/apple-icon-60x60.png'%>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_url 'app_icons/apple-icon-72x72.png'%>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_url 'app_icons/apple-icon-76x76.png'%>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_url 'app_icons/apple-icon-114x114.png'%>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_url 'app_icons/apple-icon-120x120.png'%>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_url 'app_icons/apple-icon-144x144.png'%>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_url 'app_icons/apple-icon-152x152.png'%>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_url 'app_icons/apple-icon-180x180.png'%>">
<link rel="icon" type="image/png" sizes="192x192"  href="<%= image_url 'app_icons/android-icon-192x192.png'%>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_url 'app_icons/favicon-32x32.png'%>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_url 'app_icons/favicon-96x96.png'%>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_url 'app_icons/favicon-16x16.png'%>">
<link rel="manifest" href="<%= image_url 'app_icons/manifest.json'%>">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="<%= image_url 'app_icons/ms-icon-144x144.png'%>">
<meta name="theme-color" content="#ffffff">

app/views/layouts/shared/_basket.html.haml
.basket
  - if has_order? && current_order.has_items?
    %p.quantity Det finns <b>#{articles_text(current_order)}</b> i din korg
    %p.amount <b>#{number_to_currency current_order.total_without_delivery, format: '%n %u'}</b> (exklusive frakt)
    %p.buttons
      = link_to 'Granska', basket_path
      = link_to 'Till kassan', checkout_path, class: 'checkout'

  - else
    %p.empty <b>Varukorgen är tom.</b>

app/views/layouts/shared/_meta_tags.html.erb
<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="keywords" content="<%= "#{shared_meta_keywords}#{ content_for?(:keywords) ? ",#{yield(:keywords)}" : ''}" %>">
<meta name="description" content="<%= content_for?(:description) ? yield(:description) : default_meta_description %>">
<meta name="author" content="<%= content_for?(:author) ? yield(:author) : 'LashQueen.se' %>">
<% if content_for?(:robots) %>
    <meta name="robots" content="<%= yield(:robots) %>">
<% end %>
<meta name="copyright" content="LashQueen.se">
<meta name="coverage" content="Worldwide">
<meta name="distribution" content="Global">
<meta name="application-name" content="LashQueen.se e-commerce site">

<meta property="og:title" content="<%= content_for?(:title) ? yield(:title) : 'LashQueen.se' %>"/>
<meta property="og:type" content="<%= params[:controller] == 'products' ? 'product' : 'website' %>"/>
<meta property="og:url" content="<%= request.original_url %>"/>
<meta property="og:site_name" content="LashQueen.se"/>
<meta property="og:description" content="<%= content_for?(:description) ? yield(:description) : default_meta_description %>">
<meta property="og:image" content="<%= asset_path 'screenshot.png' %>">

<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="<%= content_for?(:title) ? yield(:title) : 'LashQueen.se' %>"/>
<meta name="twitter:url" content="<%= request.original_url %>">
<meta name="twitter:site" content="@LashQueen">
<meta name="twitter:image:src" content="<%= asset_path 'screenshot.png' %>">
<% if content_for?(:twitter_creator) %>
    <meta name="twitter:creator" content="<%= yield(:twitter_creator) %>">
<% end %>
<meta name="twitter:description" content="<%= content_for?(:description) ? yield(:description) : default_meta_description %>">

app/views/layouts/shared/_order_items.html.haml
%table.orderItems
  %thead
    %tr
      %td Antal
      %td Vara
      %td Pris
      %td= Shoppe.settings.tax_name
      %td Totalt
  %tbody
    - for item in order.order_items
      %tr
        %td.quantity
          - unless defined?(readonly)
            %span
              = link_to '+', adjust_basket_item_quantity_path(item.id), method: :post, class: 'ajax'
              = link_to '-', adjust_basket_item_quantity_path(item.id), method: :delete, class: 'ajax'
          = item.quantity
        %td.product
          = item.ordered_item.full_name
          - unless defined?(readonly)
            = link_to 'Ta bort', remove_basket_item_path(item), method: :delete, class: 'delete ajax'
        %td.money.price= number_to_currency item.sub_total, format: '%n %u'
        %td.money.tax= number_to_currency item.tax_amount, format: '%n %u'
        %td.money.total= number_to_currency item.total, format: '%n %u'
  %tfoot
    - if order.delivery_service
      %tr.delivery
        %td.method{colspan: 4}
          - if defined?(readonly)
            = order.delivery_service.name
          - else
            = form_tag change_delivery_service_path do
              = select_tag 'delivery_service', options_from_collection_for_select(order.available_delivery_services, :id, :name, order.delivery_service.id)
        %td.money= number_to_currency order.delivery_price, format: '%n %u'
    %tr.subtotal
      %td{:colspan => 4} Total (exklusive #{Shoppe.settings.tax_name})
      %td.money= number_to_currency order.total_before_tax, format: '%n %u'
    %tr.tax
      %td{:colspan => 4}= Shoppe.settings.tax_name
      %td.money= number_to_currency order.tax, format: '%n %u'
    %tr.total
      %td{:colspan => 4} Total
      %td.money= number_to_currency order.total, format: '%n %u'

app/views/layouts/shared/_product_list.html.erb
<ul class="products">
  <% for product in products.includes(:default_image, :product_categories) %>
      <li>
        <div class="img" style="<%= product_image_class(product) %>; margin-left: 10px; margin-right: 10px;"></div>
        <h4>
          <%= link_to product.name, product_path(product.product_category.permalink, product.permalink) %>
        </h4>

        <p class="info">
          <%= truncate product.short_description, length: 90 %>
        </p>

        <p class="buttons">
          <%= link_to 'Info', product_path(product.product_category.permalink, product.permalink) %>
          <% if product.orderable? %>
              <%= link_to 'Lägg till', buy_product_path(product.product_category.permalink, product.permalink), class: 'add', method: :post %>
          <% end %>
        </p>
        <% unless product.has_variants? %>
            <p class="price">
              <%= "#{number_to_currency product.price_including_tax, format: '%n %u' }" %>
            </p>
        <% end %>
      </li>
  <% end %>
</ul>

      

app/views/layouts/shared/_reasons.html.haml
%ul.reasons
  %li.quality
    %h4 Högsta kvalitet
    %p Alla produkter i denna shop är noga utvalda av oss och vi använder dem själva för våra kunder..
  %li.delivery
    %h4 Snabb leverans
    %p Beställ innan kl 15.00 skickar vi varorna redan samma dag.
  %li.support
    %h4 Kunnig support
    %p Vi finns här för att hjälpa dig och delar gärma med oss av våra erfarenheter.