config/routes.rb
Rails.application.routes.draw do
    mount Shoppe::Engine => "/admin"
  
    get 'products' => 'products#categories', :as => 'catalogue'
    get 'products/filter' => 'products#filter', :as => 'product_filter'
    get 'products/:category_id' => 'products#index', :as => 'products'
    get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
    post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
    

    #
    # Order status
    #
    get 'order/:token' => 'orders#status', :as => 'order_status'

    #
    # Basket
    #
    get 'basket' => 'orders#show', :as => 'basket'
    delete 'basket' => 'orders#destroy', :as => 'empty_basket'
    post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
    delete 'basket/:order_item_id' => 'orders#change_item_quantity'
    delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
    #
    # Checkout
    #
    match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
    match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
    match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch, :post]
    match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]
  
    #
    # Static pages
    #
    #get ':action', :controller => 'pages', :as => 'page'
  
    # 
    # Homepage
    #
    root :to => 'pages#home'
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_filter do
    if params[:category_id]
      @product_category = Shoppe::ProductCategory.where(:permalink => params[:category_id]).first!
    end
    if @product_category && params[:product_id]
      @product = @product_category.products.where(:permalink => params[:product_id]).active.first!      
    end
  end
  
  def index
    @products = @product_category.products.includes(:default_image, :product_categories, :variants).root.active
    respond_to do |wants|
      wants.html { render :show }
      wants.mobile { render :show }
    end
  end
  
  def filter
    @products = Shoppe::Product.active.with_attributes(params[:key].to_s, params[:value].to_s)
  end
  
  def categories
    @product_categories = Shoppe::ProductCategory.ordered.includes(:image)
  end
  
  def show
    @attributes = @product.product_attributes.public.to_a
    respond_to do |wants|
      wants.html { render :show }
      wants.js
      wants.mobile { render :show }
    end
  end
  
  def add_to_basket
    product_to_order = params[:variant] ? @product.variants.find(params[:variant].to_i) : @product
    current_order.order_items.add_item(product_to_order, params[:quantity].blank? ? 1 : params[:quantity].to_i)
    respond_to do |wants|
      wants.html { redirect_to request.referer, alert: 'Produkten har lagts i din varukorg'  }
      wants.json { render json: {added: true} }
      wants.mobile { redirect_to request.referer, alert: 'Produkten har lagts i din varukorg' }
    end
  rescue Shoppe::Errors::NotEnoughStock => e
    message = "Tyvärr har vi inte tillräckligt av denna vara på lager. Just nu finns #{e.available_stock} st. på lager."
    respond_to do |wants|
      wants.html { redirect_to request.referer, alert: message }
      wants.json { render json: {error: 'NotEnoughStock', available_stock: e.available_stock}}
      wants.mobile { redirect_to request.referer, alert: message }
    end
  end
  
end

app/helpers/products_helper.rb
module ProductsHelper

  def product_image_class(product)
    product.default_image ? "background-image:url(#{product.default_image.path})" : ''
  end
end

app/views/products/categories.html.haml
- active_nav_item :catalogue
- @page_title = 'Katalog'
.categories
  %ul
    - for category in @product_categories
      %li
        %div.img{:style => category.image ? "background-image:url(#{category.image.path})" : 'background-color:#efefef'}
        .space
          %h4= link_to category.name, products_path(category.permalink)
          %small{style: 'font-size: 10px;'}= category.products.any? ? "Det finns #{category.products.count} produkter i denna kategori" : 'Inga produkter i denna kategori...'
          %p= category.description
      

app/views/products/filter.html.haml
- active_nav_item :catalogue
- @page_title = "#{params[:value]} - Produkter"
.category
  %h2 Products
  %p.intro Displaying products where <b>#{params[:key]}</b> is <b>#{params[:value]}</b>.
  - if @products.empty?
    %p.noProducts There are no products matching your filter
  - else
    = render 'shared/product_list', :products => @products

app/views/products/index.html.erb
<% active_nav_item :catalogue %>
<% @page_title = @product_category.name %>
<div class="category">
  <h2>
    <%= @product_category.name %>
  </h2>
  <% unless @product_category.description.blank? %>
    <p class="intro">
      <%= @product_category.description %>
    </p>
  <% end %>
  <% if @products.empty? %>
    <p class="noProducts">Det finns inga produkter i denna kategori</p>
  <% else %>
    <%= render 'shared/product_list', products: @products %>
  <% end %>
</div>

app/views/products/show.html.erb
<% active_nav_item :catalogue %>
<% @page_title = @product.name + ' - ' + @product.product_category.name %>

<div class="product">
  <% if @product.default_image %>
      <div class="img" style="background-image:url(<%= @product.default_image.path %>)"></div>
  <% end %>
  <h2>
    <%= @product.name %>
  </h2>

  <p class="intro">
    <%= @product.short_description %>
  </p>
  <% if @product.has_variants? %>
      <table class="variants">
        <% for variant in @product.variants %>
            <tr>
              <% if variant.default_image %>
                  <td class="image" style="background-color: #ffffff; background-image:url(<%= variant.default_image.path %>); background-repeat: no-repeat; background-size: auto 100%; background-position: center 0;">
                  </td>
              <% end %>
              <td>
                <% if variant.in_stock? %>
                    <p class="stock yes">I lager</p>
                <% else %>
                    <p class="stock no">Restnoterad</p>
                <% end %>
                <h4>
                  <%= variant.name %>
                </h4>
                <p class="price">
                  <%= number_to_currency variant.price_including_tax, format: '%n %u'  %>
                </p>
              </td>
              <td class="buy">
                <%= form_tag buy_product_path(@product.product_category.permalink, @product.permalink, variant: variant.id), class: (variant.in_stock? ? 'in-stock' : 'no-stock') do %>
                    <p>
                      <%= select_tag 'quantity', options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9]), disabled: !variant.in_stock? %>
                      <%= submit_tag 'Lägg till..', disabled: !variant.in_stock? %>
                    </p>
                <% end %>
              </td>
            </tr>
        <% end %>
      </table>
  <% else %>
      <div class="optionsBox">
        <div class="top">
          <p class="price">
            <%= number_to_currency @product.price_including_tax, format: '%n %u'  %>
          </p>
          <%= form_tag buy_product_path(@product.product_category.permalink, @product.permalink), class: (@product.in_stock? ? 'in-stock' : 'no-stock') do %>
              <p>
                <%= select_tag 'quantity', options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9]), disabled: !@product.in_stock? %>
                <%= submit_tag 'Lägg till...', disabled: !@product.in_stock? %>
              </p>
          <% end %>
        </div>
        <div class="bottom">
          <div class="stock">
            <% if @product.in_stock? %>
                <p class="yes">I lager</p>

                <p class="time">Beställ inom <b><%= time_until_next_delivery_cut_off %></b> för leverans
                  <%= next_delivery_day %>.</p>
            <% else %>
                <p class="no">Restnoterad</p>

                <p class="time">Tyvärr, denna produkt finns inte på lager <b><%= link_to 'Bevaka!' %></b> </p>
            <% end %>
          </div>
          <div class="links">
            <ul>
              <% if @product.data_sheet %>
                  <li class="item datasheet">
                    <%= link_to 'Sammansättning', @product.data_sheet.path %>
                  </li>
              <% end %>
              <% unless @product.in_the_box.blank? %>
                  <li class="item box">
                    <%= link_to 'Vad som ingår' %>
                    <div class="in_the_box">
                      <h3>Vad som ingår</h3>
                      <%= markdown @product.in_the_box %>
                    </div>
                  </li>
              <% end %>
              <li class="item ask">
                <%= mail_to Shoppe.settings.email_address, 'Ställ en fråga', subject: "Fråga om #{@product.name}" %>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <hr/>
  <% end %>
  <% unless @attributes.empty? %>
      <table class="attributes">
        <% for attribute in @attributes %>
            <tr>
              <th>
                <%= attribute.key %>
              </th>
              <td>
                <%= link_to attribute.value, product_filter_path(:key => attribute.key, :value => attribute.value) %>
              </td>
            </tr>
        <% end %>
      </table>
  <% end %>
  <div class="description">
    <%= markdown @product.description %>
  </div>
</div>

app/views/products/show.mobile.erb
<h2>
  <%= @product.name %>
</h2>

<% if @product.default_image %>
    <%= image_tag @product.default_image.path, style: 'max-height: 200px;' %>
<% end %>

<p>
  <%= @product.short_description %>
</p>
<%= form_tag buy_product_path(@product.product_category.permalink, @product.permalink), class: (@product.in_stock? ? 'in-stock' : 'no-stock') do %>
    <p>
      <%= select_tag 'quantity', options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9]), disabled: !@product.in_stock? %>
      <%= submit_tag 'Lägg till...', disabled: !@product.in_stock? %>
    </p>
<% end %>
<%= render 'layouts/shared/mobile/basket_pop' %>