config/routes.rb
Rails.application.routes.draw do
    mount Shoppe::Engine => "/admin"
  
    get 'products' => 'products#categories', :as => 'catalogue'
    get 'products/filter' => 'products#filter', :as => 'product_filter'
    get 'products/:category_id' => 'products#index', :as => 'products'
    get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
    post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
    

    #
    # Order status
    #
    get 'order/:token' => 'orders#status', :as => 'order_status'

    #
    # Basket
    #
    get 'basket' => 'orders#show', :as => 'basket'
    delete 'basket' => 'orders#destroy', :as => 'empty_basket'
    post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
    delete 'basket/:order_item_id' => 'orders#change_item_quantity'
    delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
    #
    # Checkout
    #
    match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
    match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
    match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch, :post]
    match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]
  
    #
    # Static pages
    #
    #get ':action', :controller => 'pages', :as => 'page'
  
    # 
    # Homepage
    #
    root :to => 'pages#home'
end

app/views/layouts/_panel.mobile.erb
<div data-role="panel" id="nav-panel" class="ui-panel ui-panel-position-left ui-panel-display-reveal ui-body-inherit ui-panel-animate ui-panel-open">
  <h3 style="margin-top: 0; padding-bottom: 10px !important;;"><%= Shoppe.settings.store_name %></h3>
  <ul data-role="listview">
    <li data-role="list-divider">Konto</li>
    <li><a href="#">Villkor</a></li>
    <li data-role="list-divider">Shoppen</li>
    <li><a href="#">Beställning</a></li>
    <li><a href="#">Kassan</a></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= [@page_title, Shoppe.settings.store_name].join('-') %></title>
  <%= render 'shared/meta_tags' %>
  <%= csrf_meta_tags %>
  <%= render 'shared/app_icons' %>
  <%= stylesheet_link_tag :application, media: 'all' %>
  <%= javascript_include_tag :application %>

  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic' %>
  <%= yield :head %>
  <%= yield :js %>
</head>
<body>
<%= display_flash %>

<header class="full main">
  <div class="inner">
    <!-- Primary navigation-->
    <nav class="main">
      <ul>
        <li>
          <%= link_to_unless_current 'Hem', root_path, nav_item: :home %>
        </li>
        <li>
          <%= link_to_unless_current 'Om oss', page_path(:why), nav_item: :why %>
        </li>
        <li>
          <%= link_to_unless_current 'Produkter', catalogue_path, nav_item: :catalogue, class: 'noborder' %>
          <ul>
            <% for category in procuct_categories %>
                <li>
                  <%= link_to category.name.upcase, products_path(category.permalink) %>
                </li>
            <% end %>
          </ul>
        </li>
        <% if service_category %>
            <li>
              <%= link_to service_category.name, products_path(service_category.permalink) %>
            </li>
        <% end %>
        <li>
          <%= link_to_unless_current 'Frågor & Svar', page_path(:faqs), nav_item: :faqs %>
        </li>
        <li>
          <%= link_to_unless_current 'Kontakta oss', page_path(:contact), nav_item: :contact %>
        </li>
      </ul>
      <%= link_to image_tag('cropped-plaza1.jpg', width: '250', alt: Shoppe.settings.store_name, class: 'pull-right'), root_path %>

    </nav>
    <div class="pull_left">
      <h1 style="font-family: 'Cinzel', serif; font-size: 5.5em; margin-top: -140px; margin-left: -6px;">LQ</h1>

      <h1 style="font-family: 'Cinzel', serif; font-size: 3.5em;;">LashQueen</h1>

      <p class="intro" style="font-family: 'Lovers Quarrel', cursive;font-size: 3em">Professionella produkter för
        fransförlängning. </p>
    </div>
  </div>
</header>


<!-- Main content section -->
<section class="content">
  <div class="inner">
    <!-- Sidebar -->
    <section class="sidebar">
      <% if content_for?(:sidebar) %>
          <%= yield :sidebar %>
      <% else %>
          <%= render 'shared/basket' %>
          <%= render 'shared/reasons' %>
      <% end %>
    </section>
    <!-- Primary section  -->
    <section class="primary">
      <%= yield %>
    </section>
  </div>
</section>
<!-- Footer -->
<footer class="main">
  <div class="inner">
    <!-- Useful footer links (policies etc...) -->
    <ul class="links">
      <li>
        <%= link_to_unless_current 'Villkor', page_path(:terms) %>
      </li>
      <li>
        <%= link_to_unless_current 'Din integritet', page_path(:privacy) %>
      </li>
      <li>
        <%= link_to_unless_current 'Returer och byten', page_path(:returns) %>
      </li>
      <li>
        <%= link_to_unless_current 'Frågor & Svar', page_path(:faqs) %>
      </li>
    </ul>
    <div class="callUs">
      <p>Undrar du något? Ring oss!:</p>

      <p class="number">tlf 031 100 20 30</p>

      <p>Vi har öppet alla vardagar.</p>
      <!-- Links to social media  -->
      <ul class="social">
        <li class="instagram">
          <%= link_to 'Instagram', 'https://instagram.com/salongplazadilaura/' %>
        </li>
        <li class="facebook">
          <%= link_to 'Facebook', 'https://www.facebook.com/plazadilaura' %>
        </li>
        <li class="youtube">
          <%= link_to 'Youtube', 'http://youtube.com' %>
        </li>
      </ul>
    </div>

    <div class="copyright">

    </div>
  </div>
</footer>
<!-- Copyright & trademark information -->

<div class="inner" style="color: #808080; font-size: 12px;">
  <p>Innehåll och bilder &copy; <%= Date.today.year %> LashQueen.se. Tredjeparts innehåll och bilder &copy; deras
    respektive ägare.
  </p>

  <p>Running on <%= image_tag 'social/ruby.svg', style: 'height: 11px; width: 11px;' %> on Rails
    using <%= link_to 'Shoppe', 'http://tryshoppe.com/' %>
    e-commerce engine and adopted
    by <%= link_to 'Thomas Ochman/AgileVentures', 'http://www.agileventures.org/users/thomas-ochman' %>.
  </p>
</div>

</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head></head>
<title><%= [@page_title, Shoppe.settings.store_name].join('-') %></title>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<%= stylesheet_link_tag 'mobile/application', media: 'all'%>
<%= javascript_include_tag 'mobile/mobile' %>
<%= csrf_meta_tags %>
<body data-no-turbolink>


<div data-role="page" id="page" data-url="<%= request.path %>">
  <div data-role="header" data-theme="b" class="ui-header ui-bar-b">
    <a href="#nav-panel" data-icon="bars" class="ui-link ui-btn-left ui-btn ui-icon-bars ui-btn-icon-notext ui-corner-all"></a>
    <span class="ui-title"><%= Shoppe.settings.store_name %></span>
    <a href="<%= root_path %>" data-no-turbolink = "true" data-icon="home" class="ui-link ui-btn-right ui-btn ui-icon-home ui-btn-icon-notext ui-corner-all"></a>

  </div>
  <div data-role="content">
  <%= yield %>
        <% if mobile_device? %>
          <%= link_to "Desktop version", :mobile => 0 %>
        <% else %>
          <%= link_to "Mobil version", :mobile => 1 %>
        <% end %>
  </div>

  <div data-role="footer" data-theme="b"><!-- footer -->
    <div data-role="navbar" data-iconpos="right"><!-- navbar -->
      <ul>
        <li><a href="<%= root_path %>" data-icon="home">Hem</a></li>
        <li><a href="<%= page_path(:contact) %>" data-icon="mail">Kontakt</a></li>
        <li><a href="#popupBasic" data-rel="popup" data-icon="shop" data-no-turbolink = "true">Varukorg</a></li>
      </ul>
    </div>
    <!-- /navbar -->
  </div>
  <!-- /footer -->

  <%= render 'layouts/panel' %>




</div>
</body>
</html>